source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

def appTrackingSDK
    pod 'AppTracking', :path => '../'
end

target 'AppTracking-Example' do
  appTrackingSDK
  pod 'SwiftLint'
end

target 'AppTrackingTests' do
  
end